Global:
  model_dir: ./yolov5s.onnx
  image_path: None   # If image_path is set, it will be trained directly based on unlabeled images, no need to set the COCO dataset path.
  coco_dataset_dir: dataset/coco/
  coco_train_image_dir: train2017
  coco_train_anno_path: annotations/instances_train2017.json
  coco_val_image_dir: val2017
  coco_val_anno_path: annotations/instances_val2017.json
  arch: YOLOv5

Distillation:
  alpha: 1.0
  loss: soft_label

QuantAware:
  onnx_format: true
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 3000
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05
  target_metric: 0.365
