Global:
  model_dir: ./yolov6s.onnx
  dataset_dir: dataset/coco/
  train_image_dir: train2017
  val_image_dir: val2017
  train_anno_path: annotations/instances_train2017.json
  val_anno_path: annotations/instances_val2017.json
  Evaluation: True
  arch: YOLOv6

Distillation:
  alpha: 1.0
  loss: soft_label

Quantization:
  onnx_format: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 8000
  eval_iter: 1000
  learning_rate: 
    type: CosineAnnealingDecay 
    learning_rate: 0.00003
    T_max: 8000
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 0.00004
