Global:
  model_dir: ViT_base_patch16_224_infer
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  batch_size: 16
  input_name: inputs
  reader_config: ./configs/VIT/data_reader.yml

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - softmax_12.tmp_0
  
Quantization:
  use_pact: true
  activation_bits: 8
  is_full_quantize: false
  activation_quantize_type: moving_average_abs_max
  weight_quantize_type: channel_wise_abs_max
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  - matmul
  - matmul_v2
  weight_bits: 8
  onnx_format: true
  
TrainConfig:
  epochs: 1
  eval_iter: 500
  learning_rate: 
    type: CosineAnnealingDecay 
    learning_rate: 0.015
  optimizer_builder:
    optimizer:
      type: Momentum
    weight_decay: 0.00002
  origin_metric: 0.8189
  
