repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.3.1
    hooks:
    -   id: remove-crlf
        files: .∗
    -   id: forbid-tabs
        files: \.(md|yml)$
    -   id: remove-tabs
        files: \.(md|yml)$
-   repo: https://github.com/PaddlePaddle/mirrors-yapf.git
    rev: v0.16.2
    hooks:
    -   id: yapf
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
        files: .∗
    -   id: end-of-file-fixer
        files: \.(md|yml)$
    -   id: trailing-whitespace
        files: \.(md|yml)$
-   repo: local
    hooks:
    -   id: pylint-doc-string
        name: pylint
        description: Check python docstring style using docstring_checker.
        entry: bash .hooks/pylint_pre_commit.hook
        language: system
        files: \.(py)$
-   repo: local
    hooks:
    -   id: copyright_checker
        name: copyright_checker
        entry: python .hooks/copyright.hook
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|proto|py)$
        exclude: (?!.*third_party)^.*|(?!.∗book).∗
