Global:
  model_dir: './MobileNetV1_infer'
  model_filename: 'inference.pdmodel'
  params_filename: "inference.pdiparams"
  batch_size: 128
  data_dir: '/paddle/dataset/imagenet/ILSVRC2012/'
  img_size: 224
  resize_size: 256
