Global:
  input_name: x
  model_dir: InceptionV3_infer
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  batch_size: 32
  data_dir: /ILSVRC2012
  
Distillation:
  alpha: 1.0
  loss: l2
  node:
  - softmax_1.tmp_0
ChannelPrune:
  pruned_ratio: 0.25
  criterion: l1_norm
  prune_params_name:
  - conv2d_0.w_0
  - conv2d_1.w_0
  - conv2d_2.w_0
  - conv2d_3.w_0
  - conv2d_4.w_0
  - conv2d_5.w_0
  - conv2d_6.w_0
  - conv2d_7.w_0
  - conv2d_8.w_0
  - conv2d_9.w_0
  - conv2d_10.w_0
  - conv2d_11.w_0
  - conv2d_12.w_0
  - conv2d_13.w_0
  - conv2d_14.w_0
  - conv2d_15.w_0
  - conv2d_16.w_0
  - conv2d_17.w_0
  - conv2d_18.w_0
  - conv2d_19.w_0
  - conv2d_20.w_0
  - conv2d_21.w_0
  - conv2d_22.w_0
  - conv2d_23.w_0
  - conv2d_24.w_0
  - conv2d_25.w_0
  - conv2d_26.w_0
  - conv2d_27.w_0
  - conv2d_28.w_0
  - conv2d_29.w_0
  - conv2d_30.w_0
  - conv2d_31.w_0
  - conv2d_32.w_0
  - conv2d_33.w_0
  - conv2d_34.w_0
  - conv2d_35.w_0
  - conv2d_36.w_0
  - conv2d_37.w_0
  - conv2d_38.w_0
  - conv2d_39.w_0
  - conv2d_40.w_0
  - conv2d_41.w_0
  - conv2d_42.w_0
  - conv2d_43.w_0
  - conv2d_44.w_0
  - conv2d_45.w_0
  - conv2d_46.w_0
  - conv2d_47.w_0
  - conv2d_48.w_0
  - conv2d_49.w_0
  - conv2d_50.w_0
  - conv2d_51.w_0
  - conv2d_52.w_0
  - conv2d_53.w_0
  - conv2d_54.w_0
  - conv2d_55.w_0
  - conv2d_56.w_0
  - conv2d_57.w_0
  - conv2d_58.w_0
  - conv2d_59.w_0
  - conv2d_60.w_0
  - conv2d_61.w_0
  - conv2d_62.w_0
  - conv2d_63.w_0
  - conv2d_64.w_0
  - conv2d_65.w_0
  - conv2d_66.w_0
  - conv2d_67.w_0
  - conv2d_68.w_0
  - conv2d_69.w_0
  - conv2d_70.w_0
  - conv2d_71.w_0
  - conv2d_72.w_0
  - conv2d_73.w_0
  - conv2d_74.w_0
  - conv2d_75.w_0
  - conv2d_76.w_0
  - conv2d_77.w_0
  - conv2d_78.w_0
  - conv2d_79.w_0
  - conv2d_80.w_0
  - conv2d_81.w_0
  - conv2d_82.w_0
  - conv2d_83.w_0
  - conv2d_84.w_0
  - conv2d_85.w_0
  - conv2d_86.w_0
  - conv2d_87.w_0
  - conv2d_88.w_0
  - conv2d_89.w_0
  - conv2d_90.w_0
  - conv2d_91.w_0
  - conv2d_92.w_0
  - conv2d_93.w_0
TrainConfig:
  epochs: 1
  eval_iter: 500
  learning_rate: 
    type: CosineAnnealingDecay 
    learning_rate: 0.015
  optimizer_builder:
    optimizer:
      type: Momentum
    weight_decay: 0.00002
  origin_metric: 0.7914
