Global:
  reader_config: configs/dataset/cityscapes_1024x512_scale1.0.yml

Distillation:
  alpha: 1.0
  loss: l2
  node: 
  - conv2d_613.tmp_1

UnstructurePrune:
  prune_strategy: gmp
  prune_mode: ratio
  ratio: 0.75
  gmp_config: 
    stable_iterations: 0
    pruning_iterations: 4500
    tunning_iterations: 4500
    resume_iteration: -1
    pruning_steps: 100
    initial_ratio: 0.15
  prune_params_type: conv1x1_only
  local_sparsity: True

TrainConfig:
  epochs: 14
  eval_iter: 90
  learning_rate: 
    type: PiecewiseDecay
    boundaries: [4500]
    values: [0.0005, 0.00025]
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 0.0005
