model:
  type: PPHumanSegLite
  align_corners: False
  num_classes: 2

batch_size: 128

train_dataset:
  type: Dataset
  dataset_root: data/humanseg
  train_path: data/humanseg/train.txt
  num_classes: 2
  transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [398, 224]
  - type: ResizeStepScaling
    scale_step_size: 0
  - type: RandomRotation
  - type: RandomPaddingCrop
    crop_size: [398, 224]
  - type: RandomHorizontalFlip
  - type: RandomDistort
  - type: RandomBlur
    prob: 0.3
  - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/humanseg
  train_path: data/humanseg/val.txt
  num_classes: 2
  transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [398, 224]
  - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: Normalize
