Global:
  model_dir: ./UIE
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: afqmc
  dataset: clue
  batch_size: 16
  max_seq_length: 128


HyperParameterOptimization:
  batch_num:
  - 4
  - 16
  bias_correct:
  - true
  hist_percent:
  - 0.999
  - 0.99999
  max_quant_count: 20
  ptq_algo:
  - KL
  - hist
  weight_quantize_type:
  - channel_wise_abs_max