
Global:
  reader_config: configs/yolo_reader.yml
  arch: PPYOLOE
  include_nms: False
  Evaluation: True
  model_dir: ./ppyoloe_crn_s_300e_coco
  model_filename: model.pdmodel
  params_filename: model.pdiparams

# Distillation:
#   alpha: 1.0
#   loss: soft_label

# QuantAware:
#   onnx_format: true
#   use_pact: true
#   activation_quantize_type: 'moving_average_abs_max'
#   quantize_op_types:
#   - conv2d
#   - depthwise_conv2d

# TrainConfig:
#   train_iter: 5000
#   eval_iter: 1000
#   learning_rate:  
#     type: CosineAnnealingDecay
#     learning_rate: 0.00003
#     T_max: 6000
#   optimizer_builder:
#     optimizer: 
#       type: SGD
#     weight_decay: 4.0e-05
QuantPost:
    batch_size: 32
    batch_nums: None
    algo: 'hist'
    hist_percent: 0.999
    bias_correct: False
    recon_level: None
    regions: None
    epochs: 20
    lr: 0.1
    simulate_activation_quant: False
    skip_tensor_list: None

