Global:
  model_dir: ./afqmc
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: afqmc
  dataset: clue
  batch_size: 16
  max_seq_length: 128
TrainConfig:
  epochs: 6
  eval_iter: 1070
  learning_rate: 2.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.7403
