Global:
  model_dir: ./iflytek
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: iflytek
  dataset: clue
  batch_size: 16
  max_seq_length: 128
TrainConfig:
  epochs: 12
  eval_iter: 750
  learning_rate: 2.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.6021
