#!/bin/bash  
# export CUDA_VISIBLE_DEVICES=0,1,2,3 
# export FLAGS_fraction_of_gpu_memory_to_use=0.98
python3.7 train_parameters_easy.py \
          --batch_size 256 \
          --data imagenet \
          --pruning_mode ratio \
          --ratio 0.75 \
          --lr 0.005 \
          --pretrained_model /code/docker-volumn/models/pretrained_model/MobileNetV1_pretrained \
          --model MobileNet \
          --num_epochs 108 \
          --test_period 5 \
          --model_path "./models" \
          --initial_ratio 0.15 \
          --stable_epochs 0 \
          --pruning_epochs 54 \
          --tunning_epochs 54 \
          --step_epochs 71 88
