Global:
  reader_config: configs/dataset/cityscapes_1024x512_scale1.0.yml
  model_dir: ./BiSeNetV2
  model_filename: model.pdmodel
  params_filename: model.pdiparams
  batch_size: 4

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - conv2d_103.tmp_1

QuantAware:
  onnx_format: True
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 5
  eval_iter: 360
  logging_iter: 100
  learning_rate: 
    type: PiecewiseDecay
    boundaries: [2]
    values: [0.00001, 0.000001]
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 0.0005