input_list: ['image']
arch: PPYOLOE                          # When export exclude_nms=True, need set arch: PPYOLOE
model_dir: ./ppyoloe_crn_s_300e_coco
model_filename: model.pdmodel
params_filename: model.pdiparams
save_dir: ./analysis_results_ppyoloe
metric: COCO
num_classes: 80
plot_hist: True
get_target_quant_model: False
target_metric: None

PTQ:
  quantizable_op_type: ["conv2d", "depthwise_conv2d"]
  weight_quantize_type: 'abs_max'
  activation_quantize_type: 'moving_average_abs_max'
  is_full_quantize: False
  batch_size: 32
  batch_nums: 10

# Datset configuration
EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /paddle/dataset/coco/

# Small Dataset to accelerate analysis
# If not exist, delete the dict of FastEvalDataset
FastEvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/small_instances_val2017.json
    dataset_dir: /dataset/coco/

worker_num: 0

# preprocess reader in test
EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1