input_list: ['image', 'scale_factor','im_shape']
model_dir: ./yolov3_r50vd_dcn_270e_coco
model_filename: model.pdmodel
params_filename: model.pdiparams
metric: COCO
num_classes: 80

# Datset configuration
TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: /work/GETR-Lite-paddle-new/inference/datasets/coco/

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /work/GETR-Lite-paddle-new/inference/datasets/coco/

eval_height: &eval_height 608
eval_width: &eval_width
eval_size: &eval_size [*eval_height, *eval_width]

worker_num: 0

# preprocess reader in test
EvalReader:
  inputs_def:
    image_shape: [1, 3, *eval_height, *eval_width]
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: *eval_size, keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 4