
Global:
  reader_config: configs/yolov6_reader.yml
  input_list: {'image': 'x2paddle_image_arrays'}
  Evaluation: True
  arch: 'YOLOv6'
  model_dir: ./yolov6s_infer
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: soft_label

Quantization:
  onnx_format: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 8000
  eval_iter: 1000
  learning_rate: 
    type: CosineAnnealingDecay 
    learning_rate: 0.00003
    T_max: 8000
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 0.00004
