
Global:
  reader_config: configs/yolo_reader.yml
  input_list: ['image', 'scale_factor']
  Evaluation: True
  model_dir: ./ppyoloe_crn_l_300e_coco/
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - concat_15.tmp_0
  - concat_14.tmp_0
  teacher_model_dir: ./ppyoloe_crn_l_300e_coco/
  teacher_model_filename: model.pdmodel
  teacher_params_filename: model.pdiparams

Quantization:
  use_pact: true
  activation_bits: 8
  weight_bits: 8
  activation_quantize_type: 'range_abs_max'
  weight_quantize_type: 'channel_wise_abs_max'
  is_full_quantize: false
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 1
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05

