
Global:
  reader_config: configs/yolo_reader.yml
  input_list: ['image', 'scale_factor']
  Evaluation: True
  model_dir: ./ppyoloe_crn_l_300e_coco
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  node:
  - concat_15.tmp_0
  - concat_14.tmp_0

Quantization:
  use_pact: true
  activation_quantize_type: 'range_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 3000
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05

