Global:
  reader_config: configs/tinypose_reader.yml
  input_list: ['image']
  Evaluation: False
  model_dir: ./tinypose_128x96
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2
  node:
  -  conv2d_441.tmp_0

Quantization:
  activation_quantize_type: 'range_abs_max'
  weight_quantize_type: 'abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 1
  eval_iter: 1000
  learning_rate: 0.0001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05
  #origin_metric: 0.291

