
Global:
  reader_config: configs/yolov5_reader.yml
  input_list: {'image': 'x2paddle_images'}
  Evaluation: True
  arch: 'YOLOv5'
  model_dir: ./yolov5s_infer/
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - conv2d_106.tmp_1
  - conv2d_113.tmp_1
  - conv2d_119.tmp_1

Quantization:
  use_pact: true
  activation_quantize_type: 'range_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 1
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05
  target_metric: 0.365
