
Global:
  reader_config: configs/yolov5_reader.yml
  input_list: {'image': 'x2paddle_images'}
  Evaluation: True
  arch: 'YOLOv5'
  model_dir: ./yolov5s_infer/
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  distill_lambda: 1.0
  distill_loss: l2_loss
  distill_node_pair:
  - teacher_conv2d_106.tmp_1
  - conv2d_106.tmp_1
  - teacher_conv2d_113.tmp_1
  - conv2d_113.tmp_1
  - teacher_conv2d_119.tmp_1
  - conv2d_119.tmp_1
  merge_feed: true
  teacher_model_dir: ./yolov5_inference_model/
  teacher_model_filename: model.pdmodel
  teacher_params_filename: model.pdiparams

Quantization:
  use_pact: true
  activation_bits: 8
  weight_bits: 8
  activation_quantize_type: 'range_abs_max'
  weight_quantize_type: 'channel_wise_abs_max'
  is_full_quantize: false
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 1
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer: SGD
  optim_args:
    weight_decay: 4.0e-05
  target_metric: 0.365
