TrainConfig:
 epochs: 14
 eval_iter: 90
 learning_rate: 
   type: PiecewiseDecay
   boundaries: [900]
   values: [0.001, 0.0005]
 optimizer_builder:
   optimizer: 
     type: SGD
   weight_decay: 0.0005  
