Distillation:
  alpha: 1.0
  loss: l2
  node: 
  - conv2d_95.tmp_0

UnstructurePrune:
  prune_strategy: gmp
  prune_mode: ratio
  ratio: 0.75
  gmp_config: 
    stable_iterations: 0
    pruning_iterations: 4500
    tunning_iterations: 4500
    resume_iteration: -1
    pruning_steps: 100
    initial_ratio: 0.15
  prune_params_type: conv1x1_only
  local_sparsity: True

TrainConfig:
  epochs: 50
  eval_iter: 180
  learning_rate: 
    type: PiecewiseDecay
    boundaries: [4500]
    values: [0.0025, 0.00025]
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 0.0005
