Global:
  input_name: input
  model_dir: inference_model_usex2paddle
  model_filename: model.pdmodel
  params_filename: model.pdiparams
  batch_size: 32
  data_dir: ./ILSVRC2012
Distillation:
  alpha: 1.0
  loss: l2
  node:
  - batch_norm_0.tmp_3
  - batch_norm_1.tmp_3
  - batch_norm_2.tmp_3
  - batch_norm_3.tmp_3
  - batch_norm_4.tmp_3
  - batch_norm_5.tmp_3
  - batch_norm_6.tmp_3
  - batch_norm_7.tmp_3
  - batch_norm_8.tmp_3
  - batch_norm_9.tmp_3
  - batch_norm_10.tmp_3
  - batch_norm_11.tmp_3
  - batch_norm_12.tmp_3
  - batch_norm_13.tmp_3
  - batch_norm_14.tmp_3
  - batch_norm_15.tmp_3
  - batch_norm_16.tmp_3
  - batch_norm_17.tmp_3
  - batch_norm_18.tmp_3
  - batch_norm_19.tmp_3
  - batch_norm_20.tmp_3
  - batch_norm_21.tmp_3
  - batch_norm_22.tmp_3
  - batch_norm_23.tmp_3
  - batch_norm_24.tmp_3
  - batch_norm_25.tmp_3
  - batch_norm_26.tmp_3
  - conv2d_42.tmp_1

QuantAware:
  use_pact: true
  activation_bits: 8
  is_full_quantize: false
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  weight_bits: 8
  activation_quantize_type: moving_average_abs_max
  weight_quantize_type: channel_wise_abs_max

TrainConfig:
  epochs: 1000
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer_builder: 
    optimizer:
      type: SGD
    weight_decay: 4.0e-05
  origin_metric: 0.71028
