Global:
  model_dir: ./yolov5s.onnx
  dataset_dir: dataset/coco/
  train_image_dir: train2017
  val_image_dir: val2017
  train_anno_path: annotations/instances_train2017.json
  val_anno_path: annotations/instances_val2017.json
  Evaluation: True

Distillation:
  alpha: 1.0
  loss: soft_label

Quantization:
  onnx_format: true
  use_pact: true
  onnx_format: False
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 3000
  eval_iter: 1000
  learning_rate: 0.00001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05
  target_metric: 0.365
