model_dir: ./yolov6s.onnx
save_dir: ./analysis_results
quantizable_op_type: ["conv2d", "depthwise_conv2d"]
weight_quantize_type: 'channel_wise_abs_max'
activation_quantize_type: 'moving_average_abs_max'
is_full_quantize: False
dataset_dir: /paddle/dataset/coco/
val_image_dir: val2017
val_anno_path: annotations/instances_val2017.json
batch_size: 10