arch: YOLOv6
model_dir: ./yolov6s.onnx
save_dir: ./analysis_results
dataset_dir: /dataset/coco/
val_image_dir: val2017
val_anno_path: annotations/instances_val2017.json

PTQ:
  quantizable_op_type: ["conv2d", "depthwise_conv2d"]
  weight_quantize_type: 'abs_max'
  activation_quantize_type: 'moving_average_abs_max'
  is_full_quantize: False
  batch_size: 10
  batch_nums: 10

