
Global:
  reader_config: configs/yolo_416_reader.yml
  exclude_nms: True
  Evaluation: True
  model_dir: ./ppyoloe_s_no_postprocess_416/ 
  model_filename: model.pdmodel
  params_filename: model.pdiparams

PTQ:  # Post Training Quantization
  quantizable_op_type: ["conv2d", "depthwise_conv2d"]
  activation_quantize_type: 'moving_average_abs_max'
  algo: avg
  is_full_quantize: True
  onnx_format: False
  batch_size: 10
  batch_nums: 10

Distillation:
  alpha: 1.0
  loss: soft_label

QuantAware:   # Auto Compression
  onnx_format: true
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 5000
  eval_iter: 1000
  learning_rate:  
    type: CosineAnnealingDecay
    learning_rate: 0.00003
    T_max: 6000
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05

