_BASE_: [
  './coco_dataset.yml',
]

worker_num: 4

TestReader:
  inputs_def:
    image_shape: [3, 384, 608]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [384, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 16
