Distillation:
  distill_lambda: 1.0
  distill_loss: l2_loss
  distill_node_pair:
  - teacher_conv2d_139.tmp_0
  - conv2d_139.tmp_0
  - teacher_conv2d_136.tmp_0
  - conv2d_136.tmp_0
  merge_feed: true
  teacher_model_dir: ./yolofastest/
  teacher_model_filename: model.pdmodel
  teacher_params_filename: model.pdiparams
Quantization:
  activation_bits: 8
  is_full_quantize: false
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  weight_bits: 8
TrainConfig:
  epochs: 1
  eval_iter: 1000
  learning_rate: 0.0001
  optimizer: SGD
  optim_args:
    weight_decay: 4.0e-05
  #origin_metric: 0.289

