Global:
  model_dir: ./CSL
  model_filename: infer.pdmodel
  params_filename: infer.pdiparams
  task_name: csl
  dataset: clue
  batch_size: 16
  max_seq_length: 128
TrainConfig:
  epochs: 16
  eval_iter: 1000
  learning_rate: 1.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.8160
