Global:
  model_dir: ./TNEWS
  model_filename: infer.pdmodel
  params_filename: infer.pdiparams
  task_name: tnews
  dataset: clue
  batch_size: 16
  max_seq_length: 128

# 剪枝
Prune:
  prune_algo: transformer_pruner
  pruned_ratio: 0.25

# 离线量化
QuantPost:
  activation_bits: 8
  quantize_op_types:
  - depthwise_conv2d
  - conv2d
  weight_bits: 8
  
