Global:
  model_dir: ./afqmc
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: afqmc
  dataset: clue
  batch_size: 16
  max_seq_length: 128

#离线量化
QuantPost:
  activation_bits: 8
  quantize_op_types: 
  - conv2d
  - depthwise_conv2d
  weight_bits: 8