Global:
  model_dir: ./ocnli
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: ocnli
  dataset: clue
  batch_size: 16
  max_seq_length: 128
TransformerPrune:
  pruned_ratio: 0.25
HyperParameterOptimization:
Distillation:
Quantization:
TrainConfig:
  epochs: 20
  eval_iter: 1050
  learning_rate: 3.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.7620
