Global:
  model_dir: ./tnews
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: tnews
  dataset: clue
  batch_size: 16
  max_seq_length: 128
TransformerPrune:
  pruned_ratio: 0.25
HyperParameterOptimization:
Distillation:
QuantPost:
TrainConfig:
  epochs: 6
  eval_iter: 1110
  learning_rate: 2.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.5666
