Global:
  reader_config: configs/dataset/cityscapes_1024x512_scale1.0.yml

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - conv2d_123.tmp_1

Quantization:
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 10
  eval_iter: 360
  learning_rate: 0.0001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 0.0005
