Global:
  reader_config: configs/deeplabv3/deeplabv3_reader.yml
  model_dir: ./RES-paddle2-Deeplabv3-ResNet50
  model_filename: model
  params_filename: params

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - conv2d_123.tmp_1

Quantization:
  onnx_format: True
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 1
  eval_iter: 360
  learning_rate: 0.0001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 0.0005