Data:
  Eval:
    dataset:
      name: GPTDataset
      input_dir: ./lambada_test.jsonl 
      max_seq_len: 1024
      overlapping_eval: 32
    loader:
      num_workers: 1
      return_list: True
      collate_fn: gpt_collate_fn
      batch_size: 1
      